---
######################################
# Created by : Meir
# Purpose : Ansible Summary Pratice 05
# Date : 17/5/2025
# Version : 1
######################################
- name: Copy and execute hello.sh on all servers
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  pre_tasks:
    - name: Check if /tmp directory exists
      stat:
        path: /tmp
      register: tmp_dir

  tasks:
    - name: Copy hello.sh from the current directory to /tmp
      copy:
        src: ./hello.sh
        dest: /tmp/hello.sh
        mode: '0755'
      when: tmp_dir.stat.exists == true

    - name: Execute hello.sh script remotely
      shell: /tmp/hello.sh
      when: tmp_dir.stat.exists == true
      register: result

    - name: Show the output of the hello.sh script
      debug:
        msg: "{{ result.stdout }}"
      when: tmp_dir.stat.exists == true

